
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
light: !include lights.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

lutron_caseta_pro:
    bridges:
      - host: 192.168.13.6
        mac: 64:cf:d9:c5:ce:80

